// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssywclcgntzjjwudmzrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeXdjbGNnbnR6amp3dWRtenJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mzg2MTQsImV4cCI6MjA2NjQxNDYxNH0.fsLM5hKxtBiYN2wIBx95eIZ93O2N3TW2pDGEUd-tPBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);